export interface InvoiceItem {
  description: string;
  hsnSac: string;
  discountPct: number;
  taxRate: number;
  mrp: number;
  uom: string;
  quantity: number;
  price: number;
  amount: number;
}

export interface InvoiceTaxSummary {
  hsnSac: string;
  taxableValue: number;
  cgstRate: number;
  cgstAmount: number;
  sgstRate: number;
  sgstAmount: number;
  igstRate: number;
  igstAmount: number;
}

export interface Invoice {
  id?: string;
  invoiceNo: string;
  invoiceSeq: number;
  invoiceDate: any;
  dcNo: string;
  dcId?: string;
  packingListId: string;
  packingListNo: string;
  salesOrderIds: string[];
  salesNos: string[];
  orderNo: string;
  clientId: string;
  clientName: string;
  clientAddress: string;
  clientPlace: string;
  clientState: string;
  clientZipCode: string;
  clientPhone: string;
  clientGstin: string;
  destination: string;
  // Transport Master fields — see PackingList.transport/transportId for how
  // these are sourced.
  transport: string;
  transportId?: string;
  transportAddress?: string;
  transportGstNo?: string;
  vehicleNo: string;
  docNo: string;
  shipmentDate: any;
  totalPkgs: number;
  agentName: string;
  items: InvoiceItem[];
  grossAmount: number;
  discountPct: number;
  discountAmount: number;
  taxableValue: number;
  cgstRate: number;
  cgstAmount: number;
  sgstRate: number;
  sgstAmount: number;
  igstRate: number;
  igstAmount: number;
  totalTaxAmount: number;
  roundOff: number;
  totalAmount: number;
  amountInWords: string;
  taxSummary: InvoiceTaxSummary[];
  // E-Invoice fields — populated by EInvoiceService via the generateEInvoiceIrn/
  // cancelEInvoiceIrn Cloud Functions, which proxy Webtel's GenIRN2/CanIRN
  // sandbox APIs (browser can't call them directly: mixed-content HTTP +
  // no CORS + credential exposure).
  eInvoiceStatus?: 'pending' | 'generated' | 'failed' | 'cancelled';
  irn?: string;
  irnGeneratedAt?: any;
  ackNo?: string;
  ackDt?: string;
  signedQrCode?: string;
  // Signed JWT of the full invoice as returned by the IRP/Webtel — kept
  // separately from signedQrCode (which is the renderable QR image).
  signedInvoice?: string;
  eInvoicePayload?: any;
  eInvoiceErrorMessage?: string;
  eInvoiceErrorCode?: string;
  cancelReason?: string;
  cancelledAt?: any;
  // E-Way Bill fields — populated by EwayBillService via the
  // generateEwayBillByIrn/cancelEwayBill Cloud Functions (Webtel E-Way Bill
  // sandbox). Only meaningful once eInvoiceStatus === 'generated' (an
  // E-Way Bill is generated by IRN, so it depends on the e-Invoice existing).
  ewbStatus?: 'pending' | 'generated' | 'failed' | 'cancelled';
  ewbNo?: string;
  ewbGeneratedAt?: any;
  ewbDate?: string;
  ewbValidTill?: string;
  ewbGstin?: string;
  ewbTransportDetails?: EwayBillTransportDetails;
  ewbErrorMessage?: string;
  ewbErrorCode?: string;
  ewbCancelReason?: string;
  ewbCancelledAt?: any;
  createdAt?: any;
  updatedAt?: any;
}

// Transport details captured on the E-Way Bill generation form — mirrors the
// fields Webtel's GenEWaybyIRN sandbox API requires. Kept here (rather than
// in eway-bill.model.ts) to avoid a circular import, since Invoice embeds it.
export interface EwayBillTransportDetails {
  distance: number;
  transMode: '1' | '2' | '3' | '4'; // Road / Rail / Air / Ship
  transporterId?: string;
  transporterName?: string;
  vehicleNo?: string;
  vehicleType?: 'R' | 'O'; // Regular / Over-Dimensional-Cargo
  transDocNo?: string;
  transDocDt?: string;
}
